[tool.poetry]
name = "rocrate-validator"
version = "0.1.0"
description = ""
authors = ["Marco Enrico Piras <kikkomep@crs4.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rdflib = "^7.0.0"
pyshacl = "^0.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
